# frozen_string_literal: true

require "date"
require "fileutils"
require "pathname"
require "tempfile"
require "uri"
require "yaml"

module GtsamPostSync
  class SyncError < StandardError; end

  POST_FILENAME = /\A(\d{4})-(\d{2})-(\d{2})-(.+)\.(?:md|markdown|html)\z/i
  GENERATED_HEADER = "# Generated by scripts/sync_gtsam_posts.rb; do not edit by hand.\n"
  PERMALINK_STYLES = {
    "date" => "/:categories/:year/:month/:day/:title:output_ext",
    "pretty" => "/:categories/:year/:month/:day/:title/",
    "ordinal" => "/:categories/:year/:y_day/:title:output_ext",
    "weekdate" => "/:categories/:year/W:week/:short_day/:title:output_ext",
    "none" => "/:categories/:title:output_ext"
  }.freeze

  module_function

  def sync(posts_directory, output_file)
    posts_path = Pathname(posts_directory).expand_path
    output_path = Pathname(output_file).expand_path

    raise SyncError, "posts directory does not exist: #{posts_path}" unless posts_path.directory?

    config = load_yaml_file(posts_path.parent.join("_config.yml"), "site configuration")
    posts = post_files(posts_path).filter_map { |path| parse_post(path, posts_path, config) }
    raise SyncError, "no published posts found in #{posts_path}" if posts.empty?

    posts.sort_by! { |post| [-Date.iso8601(post.fetch("date")).jd, post.fetch("url")] }
    reject_duplicate_urls(posts)
    write_posts(output_path, posts)
    posts
  end

  def post_files(posts_path)
    posts_path.glob("**/*").select do |path|
      path.file? && path.basename.to_s.match?(/\.(?:md|markdown|html)\z/i)
    end.sort
  end

  def parse_post(path, posts_path, config)
    match = POST_FILENAME.match(path.basename.to_s)
    raise SyncError, "invalid post filename: #{path}" unless match

    metadata = load_front_matter(path)
    return nil if metadata["published"] == false

    date = begin
      Date.new(match[1].to_i, match[2].to_i, match[3].to_i)
    rescue Date::Error => error
      raise SyncError, "invalid date in #{path.basename}: #{error.message}"
    end

    slug = metadata.fetch("slug", match[4]).to_s.strip
    raise SyncError, "empty slug in #{path}" if slug.empty?

    title = metadata["title"].to_s.strip
    title = titleize_slug(slug) if title.empty?

    categories = directory_categories(path, posts_path) + front_matter_categories(metadata)
    permalink = metadata.fetch("permalink", config.fetch("permalink", "date"))

    {
      "title" => title,
      "date" => date.iso8601,
      "url" => canonical_url(config, permalink, date, slug, categories)
    }
  end

  def load_front_matter(path)
    lines = path.readlines
    return {} unless lines.first&.strip == "---"

    closing_index = lines.drop(1).index { |line| line.strip == "---" }
    raise SyncError, "unterminated YAML front matter in #{path}" unless closing_index

    yaml = lines[1, closing_index].join
    metadata = YAML.safe_load(yaml, permitted_classes: [Date, Time], aliases: true) || {}
    raise SyncError, "front matter must be a mapping in #{path}" unless metadata.is_a?(Hash)

    metadata
  rescue Psych::Exception => error
    raise SyncError, "invalid YAML front matter in #{path}: #{error.message.lines.first.strip}"
  end

  def titleize_slug(slug)
    slug.split(/[-_]+/).map(&:capitalize).join(" ")
  end

  def load_yaml_file(path, description)
    raise SyncError, "missing #{description}: #{path}" unless path.file?

    data = YAML.safe_load(path.read, permitted_classes: [Date, Time], aliases: true) || {}
    raise SyncError, "#{description} must be a mapping: #{path}" unless data.is_a?(Hash)

    data
  rescue Psych::Exception => error
    raise SyncError, "invalid #{description} in #{path}: #{error.message.lines.first.strip}"
  end

  def directory_categories(path, posts_path)
    relative_directory = path.dirname.relative_path_from(posts_path).to_s
    relative_directory == "." ? [] : relative_directory.split(File::SEPARATOR)
  end

  def front_matter_categories(metadata)
    raw_categories = metadata["categories"] || metadata["category"]
    case raw_categories
    when nil
      []
    when Array
      raw_categories.flatten.map(&:to_s).map(&:strip).reject(&:empty?)
    else
      raw_categories.to_s.split.map(&:strip).reject(&:empty?)
    end
  end

  def canonical_url(config, permalink, date, slug, categories)
    template = permalink.to_s.strip
    raise SyncError, "permalink cannot be empty" if template.empty?

    template = PERMALINK_STYLES.fetch(template, template)
    replacements = {
      "categories" => categories.join("/"),
      "year" => date.strftime("%Y"),
      "short_year" => date.strftime("%y"),
      "month" => date.strftime("%m"),
      "i_month" => date.month.to_s,
      "day" => date.strftime("%d"),
      "i_day" => date.day.to_s,
      "y_day" => date.strftime("%j"),
      "week" => date.strftime("%V"),
      "short_day" => date.strftime("%a").downcase,
      "title" => slug,
      "slug" => slug,
      "output_ext" => ".html"
    }

    expanded = template.gsub(/:([a-z_]+)/) do |token|
      key = Regexp.last_match(1)
      replacements.fetch(key) { raise SyncError, "unsupported permalink token #{token}" }
    end

    return normalize_absolute_url(expanded) if expanded.match?(%r{\Ahttps?://}i)

    site_origin = normalize_absolute_url(
      config.fetch("url", "https://gtsam.org").to_s,
      strip_trailing_slash: true
    )
    baseurl = normalize_path(config.fetch("baseurl", "").to_s, preserve_trailing_slash: false)
    post_path = normalize_path(expanded, preserve_trailing_slash: expanded.end_with?("/"))
    "#{site_origin.sub(%r{/\z}, "")}#{baseurl == "/" ? "" : baseurl}#{post_path}"
  rescue URI::InvalidURIError => error
    raise SyncError, "invalid URL configuration: #{error.message}"
  end

  def normalize_absolute_url(value, strip_trailing_slash: false)
    uri = URI.parse(value)
    raise SyncError, "URL must include an HTTP(S) host: #{value}" unless uri.is_a?(URI::HTTP) && uri.host

    uri.scheme = "https"
    uri.port = nil if uri.port == 80
    normalized = uri.to_s
    strip_trailing_slash ? normalized.sub(%r{/\z}, "") : normalized
  end

  def normalize_path(value, preserve_trailing_slash:)
    trailing_slash = preserve_trailing_slash && value.end_with?("/")
    segments = value.split("/").reject(&:empty?)
    path = "/#{segments.join("/")}"
    path += "/" if trailing_slash && path != "/"
    path
  end

  def reject_duplicate_urls(posts)
    duplicates = posts.group_by { |post| post.fetch("url") }.select { |_url, entries| entries.length > 1 }
    return if duplicates.empty?

    raise SyncError, "duplicate post URL(s): #{duplicates.keys.sort.join(", ")}"
  end

  def write_posts(output_path, posts)
    FileUtils.mkdir_p(output_path.dirname)
    tempfile = Tempfile.new([output_path.basename.to_s, ".tmp"], output_path.dirname)
    tempfile.write(GENERATED_HEADER)
    tempfile.write(YAML.dump(posts))
    tempfile.close
    File.rename(tempfile.path, output_path)
  ensure
    tempfile&.close
    tempfile&.unlink
  end
end

if $PROGRAM_NAME == __FILE__
  unless ARGV.length == 2
    warn "Usage: ruby scripts/sync_gtsam_posts.rb POSTS_DIRECTORY OUTPUT_FILE"
    exit 2
  end

  begin
    posts = GtsamPostSync.sync(ARGV[0], ARGV[1])
    puts "Wrote #{posts.length} GTSAM posts to #{ARGV[1]}"
  rescue GtsamPostSync::SyncError => error
    warn "GTSAM post synchronization failed: #{error.message}"
    exit 1
  end
end
